### ISSUE TITLE
Change from separate pickle file to storing memories in character json file

### ISSUE THREAD

**Issue by theubie** [theubie/complex_memory#1]
To make memories more portable, I think I should store the memories inside the character json file instead of in its own pickle file.

1.  Removed pickle files, which are security holes.
2.  Allows users to create complex memory schemes and share them easily in a single file

Thoughts?

**Comment by theubie** [comment]
This has been implemented as of commit dead3dbbf8c39971260cc688dc56d40517c57091

**Comment by remghoost** [comment]
Damn, you beat me to it. Haha.
I just got it working too.

**Comment by theubie** [comment]
I need to see if there is a way to make the file write spit out more human-readable formatting, but's more of a "would be nice".
