### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by Nic-Raf** [theubie/complex_memory#11]
The extensions worked fine, but when I update the webui. It gives me an error:
![Capture](https://user-images.githubusercontent.com/131965818/234835816-cb0879b9-bf34-46fb-853a-1af9dd061257.PNG)

**Comment by theubie** [comment]
Oooba made changes to generation again, after promising that they wouldn't.  This will keep happening, and I'll keep fixing it.  Fixed in commit 124b3533db87737bad1b4a45111c3223a802cf89
