### ISSUE TITLE
Oobabooga style update breaks complex_memory

### ISSUE THREAD

**Issue by just-someguy** [theubie/complex_memory#14]
Oobabooga released a commit that added styles to the chats, and complex memory now causes characters to load improperly. The `chat.load_character` function now includes a `style` variable and this is breaking the extension with error

> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
>     output = await app.get_blocks().process_api(
>   File "C:\Users\user\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
>     result = await self.call_function(
>   File "C:\Users\user\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 916, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "C:\Users\user\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "C:\Users\user\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "C:\Users\user\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "C:\Users\user\Desktop\oobabooga_windows\text-generation-webui\extensions\complex_memory\script.py", line 155, in load_character_complex_memory_hijack
>     result = chat.load_character(character_menu, name1, name2, mode)
> TypeError: load_character() missing 1 required positional argument: 'style'

I've tried just adding the `style` argument to line 155, and subsequently 153, 256, and 257 leading to errors that aren't likely helpful.

**Comment by theubie** [comment]
You were very close.  It's chat_style.  This should be fixed in commit 1ac69b5b5e0d4a1f8c12785173604a914c6a81f6
